name: Publish Python Package to conda

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda install -y anaconda-client conda-build
        conda install -y setuptools setuptools_scm
    - name: Update recipe with version variable
      run: |
        VERSION=$(python setup.py --version)
        LINE_STR='{% set version = "'${VERSION}'" %}'
        RECIPE_PATH='recipe/meta.yaml'
        echo $LINE_STR | cat - $RECIPE_PATH > temp && mv temp $RECIPE_PATH
    
    - name: Build and publish
      env:
        CONDA_USERNAME: ${{ secrets.CONDA_USERNAME }}
        CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
      run: |
        conda config --set anaconda_upload yes
        conda build . --token $CONDA_TOKEN --user $CONDA_USERNAME 