name: Python Package with conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Get git tags
      run:  git fetch --prune --unshallow --tags
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        $CONDA/bin/conda install -c defaults -c conda-forge -c astropy -c moeyensj --file requirements.txt --yes
    #- name: Lint with flake8
    #  run: |
    #    $CONDA/bin/conda install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install package
      run: |
        $CONDA/bin/python setup.py install  
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest . --cov=.
